# Generated by Django 6.0.3 on 2026-03-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='session_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
    ]
