# Generated by Django 6.0.3 on 2026-03-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_feedback_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='session_id',
        ),
    ]
