# Generated by Django 6.0.3 on 2026-03-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=10)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
