# Generated by Django 6.0.3 on 2026-03-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
        migrations.AddField(
            model_name='player',
            name='value',
            field=models.IntegerField(default=500),
        ),
    ]
