# Generated by Django 6.0.3 on 2026-03-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_score_player_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
