# Generated by Django 6.0.3 on 2026-03-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
