# Generated by Django 6.0.3 on 2026-03-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_player_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=30),
        ),
    ]
