# Generated by Django 6.0.3 on 2026-03-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_player_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='glicko_rating',
            field=models.FloatField(default=1500),
        ),
        migrations.AddField(
            model_name='player',
            name='glicko_rd',
            field=models.FloatField(default=350),
        ),
        migrations.AddField(
            model_name='player',
            name='glicko_vol',
            field=models.FloatField(default=0.06),
        ),
        migrations.AddField(
            model_name='player',
            name='last_rating_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
